server:
  port: 8833
spring:
  application:
    name: jlumall-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    loadbalancer:
      cache:
        enabled: true
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Path=/**

    #        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq

        - id: product_route
          uri: lb://jlumall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: coupon_route
          uri: lb://jlumall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: third_party_route
          uri: lb://jlumall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: member_route
          uri: lb://jlumall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: ware_route
          uri: lb://jlumall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: order_route
          uri: lb://jlumall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        - id: jlumall_host_route
          uri: lb://jlumall-product
          predicates:
            - Host=jlumall.com,item.jlumall.com

        - id: jlumall_search_route
          uri: lb://jlumall-search
          predicates:
            - Host=search.jlumall.com

        - id: jlumall_auth_route
          uri: lb://jlumall-auth-server
          predicates:
            - Host=auth.jlumall.com

        - id: jlumall_cart_route
          uri: lb://jlumall-cart
          predicates:
            - Host=cart.jlumall.com

        - id: jlumall_order_route
          uri: lb://jlumall-order
          predicates:
            - Host=order.jlumall.com

        - id: jlumall_member_route
          uri: lb://jlumall-member
          predicates:
            - Host=member.jlumall.com

        - id: jlumall_seckill_route
          uri: lb://jlumall-seckill
          predicates:
            - Host=seckill.jlumall.com

#暴露所有端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

  ## 前端项目，/api
## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree



