spring:
  application:
    name: jlumall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
server:
  port: 30000